name: CI / CD

on: [push]

env:
  SOLUTION_NAME: schema
  ENVIRONMENT_URL: https://githubactions.crm.dynamics.com/

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tyler-hogsett-microsoft/cds-actions-pack-solution@master
      with:
        folder: solutions\${{ env.SOLUTION_NAME }}
        zipFile: ${{ github.workspace }}\packed-solutions\${{ env.SOLUTION_NAME }}.zip
        packageType: both
#    - uses: actions/upload-artifact@v1
#      with:
#        name: packed-solutions
#        path: ${{ github.workspace }}\packed-solutions

#  deploy:
#    needs: build
#    runs-on: windows-latest
#    steps:
#    - uses: actions/download-artifact@v1
#      with:
#        name: packed-solutions
#        path: ${{ github.workspace }}\packed-solutions
#    - uses: tyler-hogsett-microsoft/cds-actions/import-solution
#      with:
#        username: ${{ secrets.CDS_SERVICE_USERNAME }}
#        password: ${{ secrets.CDS_SERVICE_PASSWORD }}
#        url: ${{ env.ENVIRONMENT_URL }}
#        zipFile: ${{ github.workspace }}\packed-solutions\${{ env.SOLUTION_NAME }}_managed.zip